version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      FLASK_ENV: development
    depends_on:
      - mongodb
      - redis
    networks:
      - app_network

  mongodb:
    image: mongo
    networks:
      - app_network

  redis:
    image: redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
