version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

